project:
  type: website
  output-dir: docs
  resources:
    - SOCIAL_SEMESTER_BOOK_EN.pdf
    - .nojekyll

website:
  description: Kostadin Kostadinov | Assistant Professor at the Medical University of Plovdiv

  page-footer:
    left: "Email me at <a href='mailto:kostadinr.kostadinov@mu-plovdiv.bg'>kostadinr.kostadinov@mu-plovdiv.bg</a> or book a <a href='https://tinyurl.com/whentomeetme' target='_blank'>meeting</a>"
  title: "Kostadin Kostadinov"
  favicon: favicon.png

  twitter-card:
    creator: "@https://x.com/kostadinoffMD"
  navbar:
    right:
      - icon: github
        href: https://github.com/kostadinoff
      - icon: twitter
        href: https://x.com/kostadinoffMD
      - icon: linkedin
        href: https://www.linkedin.com/in/kostadinovmd/
      - icon: rss
        href: epinews.xml
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: epinews.qmd
        text: Epi News
      - href: study-guide.qmd
        text: Social medicine study guide

format:
  html:
    theme:
      - darkly
      - barbie.scss
    css: styles.css
    toc: true
    sharing: [twitter, linkedin, facebook]
    comments:
      giscus:
        repo: kostadinoff/kostadinoff.github.io
    title-block-banner: true
editor: source
site-url: "https://kostadinoff.github.io"
